var map_cfg = {
 "mapWidth": "100%",
 "mapHeight": 410,
 "shadowWidth": 2,
 "shadowOpacity": 0.2,
 "shadowColor": "black",
 "shadowX": 0,
 "shadowY": 0,
 "iPhoneLink": true,
 "isNewWindow": false,
 "zoomEnable": false,
 "zoomEnableControls": false,
 "zoomIgnoreMouseScroll": false,
 "zoomMax": 8,
 "zoomStep": 0.8,
 "borderColor": "#ffffff",
 "borderColorOver": "#ffffff",
 "borderOpacity": 0.5,
 "nameColor": "#ffffff",
 "nameColorOver": "#ffffff",
 "nameFontSize": "10px",
 "nameFontWeight": "bold",
 "nameStroke": false,
 "nameStrokeColor": "#000000",
 "nameStrokeColorOver": "#000000",
 "nameStrokeWidth": 1.5,
 "nameStrokeOpacity": 0.5,
 "overDelay": 300,
 "nameAutoSize": false,
 "tooltipOnHighlightIn": false,
 "freezeTooltipOnClick": false,
 "mapId": "vcg",
 "map_data": {
  "st1": {
   "name": "Alabama",
   "shortname": "AL",
   "comment": "",
   "link": "",
   "id": 1,
   "color": "#c89666",
   "colorOver": "#2d545e"
  },
  "st2": {
   "name": "Alaska",
   "shortname": "AK ",
   "comment": "",
   "link": "",
   "id": 2,
   "color": "#c89666",
   "colorOver": "#2d545e"
  },
  "st3": {
   "name": "Arizona",
   "shortname": "AZ ",
   "comment": "",
   "link": "",
   "id": 3,
   "color": "#c89666",
   "colorOver": "#2d545e"
  },
  "st4": {
   "name": "Arkansas",
   "shortname": "AR",
   "comment": "",
   "link": "",
   "id": 4,
   "color": "#c89666",
   "colorOver": "#2d545e"
  },
  "st5": {
   "name": "California",
   "shortname": "CA",
   "comment": "",
   "link": "",
   "id": 5,
   "color": "#c89666",
   "colorOver": "#2d545e"
  },
  "st6": {
   "name": "Colorado",
   "shortname": "CO",
   "comment": "",
   "link": "",
   "id": 6,
   "color": "#c89666",
   "colorOver": "#2d545e"
  },
  "st7": {
   "name": "Connecticut",
   "shortname": "CT",
   "comment": "",
   "link": "",
   "id": 7,
   "color": "#c89666",
   "colorOver": "#2d545e"
  },
  "st8": {
   "name": "Delaware",
   "shortname": "DE",
   "comment": "",
   "link": "",
   "id": 8,
   "color": "#c89666",
   "colorOver": "#2d545e"
  },
  "st9": {
   "name": "District of Columbia",
   "shortname": "DC",
   "comment": "",
   "link": "",
   "id": 9,
   "color": "#c89666",
   "colorOver": "#2d545e"
  },
  "st10": {
   "name": "Florida",
   "shortname": "FL",
   "comment": "",
   "link": "",
   "id": 10,
   "color": "#c89666",
   "colorOver": "#2d545e"
  },
  "st11": {
   "name": "Georgia",
   "shortname": "GA",
   "comment": "",
   "link": "",
   "id": 11,
   "color": "#c89666",
   "colorOver": "#2d545e"
  },
  "st12": {
   "name": "Hawaii",
   "shortname": "HI",
   "comment": "",
   "link": "",
   "id": 12,
   "color": "#c89666",
   "colorOver": "#2d545e"
  },
  "st13": {
   "name": "Idaho",
   "shortname": "ID",
   "comment": "",
   "link": "",
   "id": 13,
   "color": "#c89666",
   "colorOver": "#2d545e"
  },
  "st14": {
   "name": "Illinois",
   "shortname": "IL",
   "comment": "",
   "link": "",
   "id": 14,
   "color": "#c89666",
   "colorOver": "#2d545e"
  },
  "st15": {
   "name": "Indiana",
   "shortname": "IN",
   "comment": "",
   "link": "",
   "id": 15,
   "color": "#c89666",
   "colorOver": "#2d545e"
  },
  "st16": {
   "name": "Iowa",
   "shortname": "IA",
   "comment": "",
   "link": "",
   "id": 16,
   "color": "#c89666",
   "colorOver": "#2d545e"
  },
  "st17": {
   "name": "Kansas",
   "shortname": "KS",
   "comment": "",
   "link": "",
   "id": 17,
   "color": "#c89666",
   "colorOver": "#2d545e"
  },
  "st18": {
   "name": "Kentucky",
   "shortname": "KY",
   "comment": "",
   "link": "",
   "id": 18,
   "color": "#c89666",
   "colorOver": "#2d545e"
  },
  "st19": {
   "name": "Louisiana",
   "shortname": "LA",
   "comment": "",
   "link": "",
   "id": 19,
   "color": "#c89666",
   "colorOver": "#2d545e"
  },
  "st20": {
   "name": "Maine",
   "shortname": "ME",
   "comment": "",
   "link": "",
   "id": 20,
   "color": "#c89666",
   "colorOver": "#2d545e"
  },
  "st21": {
   "name": "Maryland",
   "shortname": "MD",
   "comment": "",
   "link": "",
   "id": 21,
   "color": "#c89666",
   "colorOver": "#2d545e"
  },
  "st22": {
   "name": "Massachusetts",
   "shortname": "MA",
   "comment": "",
   "link": "",
   "id": 22,
   "color": "#c89666",
   "colorOver": "#2d545e"
  },
  "st23": {
   "name": "Michigan",
   "shortname": "MI",
   "comment": "",
   "link": "",
   "id": 23,
   "color": "#c89666",
   "colorOver": "#2d545e"
  },
  "st24": {
   "name": "Minnesota",
   "shortname": "MN",
   "comment": "",
   "link": "",
   "id": 24,
   "color": "#c89666",
   "colorOver": "#2d545e"
  },
  "st25": {
   "name": "Mississippi",
   "shortname": "MS",
   "comment": "",
   "link": "",
   "id": 25,
   "color": "#c89666",
   "colorOver": "#2d545e"
  },
  "st26": {
   "name": "Missouri",
   "shortname": "MO",
   "comment": "",
   "link": "",
   "id": 26,
   "color": "#c89666",
   "colorOver": "#2d545e"
  },
  "st27": {
   "name": "Montana",
   "shortname": "MT",
   "comment": "",
   "link": "",
   "id": 27,
   "color": "#c89666",
   "colorOver": "#2d545e"
  },
  "st28": {
   "name": "Nebraska",
   "shortname": "NE",
   "comment": "",
   "link": "",
   "id": 28,
   "color": "#c89666",
   "colorOver": "#2d545e"
  },
  "st29": {
   "name": "Nevada",
   "shortname": "NV",
   "comment": "",
   "link": "",
   "id": 29,
   "color": "#c89666",
   "colorOver": "#2d545e"
  },
  "st30": {
   "name": "New Hampshire",
   "shortname": "NH",
   "comment": "",
   "link": "",
   "id": 30,
   "color": "#c89666",
   "colorOver": "#2d545e"
  },
  "st31": {
   "name": "New Jersey",
   "shortname": "NJ",
   "comment": "",
   "link": "",
   "id": 31,
   "color": "#c89666",
   "colorOver": "#2d545e"
  },
  "st32": {
   "name": "New Mexico",
   "shortname": "NM",
   "comment": "",
   "link": "",
   "id": 32,
   "color": "#c89666",
   "colorOver": "#2d545e"
  },
  "st33": {
   "name": "New York",
   "shortname": "NY",
   "comment": "",
   "link": "",
   "id": 33,
   "color": "#c89666",
   "colorOver": "#2d545e"
  },
  "st34": {
   "name": "North Carolina",
   "shortname": "NC",
   "comment": "",
   "link": "",
   "id": 34,
   "color": "#c89666",
   "colorOver": "#2d545e"
  },
  "st35": {
   "name": "North Dakota",
   "shortname": "ND",
   "comment": "",
   "link": "",
   "id": 35,
   "color": "#c89666",
   "colorOver": "#2d545e"
  },
  "st36": {
   "name": "Ohio",
   "shortname": "OH",
   "comment": "",
   "link": "",
   "id": 36,
   "color": "#c89666",
   "colorOver": "#2d545e"
  },
  "st37": {
   "name": "Oklahoma",
   "shortname": "OK",
   "comment": "",
   "link": "",
   "id": 37,
   "color": "#c89666",
   "colorOver": "#2d545e"
  },
  "st38": {
   "name": "Oregon",
   "shortname": "OR",
   "comment": "",
   "link": "",
   "id": 38,
   "color": "#c89666",
   "colorOver": "#2d545e"
  },
  "st39": {
   "name": "Pennsylvania",
   "shortname": "PA",
   "comment": "",
   "link": "",
   "id": 39,
   "color": "#c89666",
   "colorOver": "#2d545e"
  },
  "st40": {
   "name": "Rhode Island",
   "shortname": "RI",
   "comment": "",
   "link": "",
   "id": 40,
   "color": "#c89666",
   "colorOver": "#2d545e"
  },
  "st41": {
   "name": "South Carolina",
   "shortname": "SC",
   "comment": "",
   "link": "",
   "id": 41,
   "color": "#c89666",
   "colorOver": "#2d545e"
  },
  "st42": {
   "name": "South Dakota",
   "shortname": "SD",
   "comment": "",
   "link": "",
   "id": 42,
   "color": "#c89666",
   "colorOver": "#2d545e"
  },
  "st43": {
   "name": "Tennessee",
   "shortname": "TN",
   "comment": "",
   "link": "",
   "id": 43,
   "color": "#c89666",
   "colorOver": "#2d545e"
  },
  "st44": {
   "name": "Texas",
   "shortname": "TX",
   "comment": "",
   "link": "",
   "id": 44,
   "color": "#c89666",
   "colorOver": "#2d545e"
  },
  "st45": {
   "name": "Utah",
   "shortname": "UT",
   "comment": "",
   "link": "",
   "id": 45,
   "color": "#c89666",
   "colorOver": "#2d545e"
  },
  "st46": {
   "name": "Vermont",
   "shortname": "VT",
   "comment": "",
   "link": "",
   "id": 46,
   "color": "#c89666",
   "colorOver": "#2d545e"
  },
  "st47": {
   "name": "Virginia",
   "shortname": "VA",
   "comment": "",
   "link": "",
   "id": 47,
   "color": "#c89666",
   "colorOver": "#2d545e"
  },
  "st48": {
   "name": "Washington",
   "shortname": "WA",
   "comment": "",
   "link": "",
   "id": 48,
   "color": "#c89666",
   "colorOver": "#2d545e"
  },
  "st49": {
   "name": "West Virginia",
   "shortname": "WV",
   "comment": "",
   "link": "",
   "id": 49,
   "color": "#c89666",
   "colorOver": "#2d545e"
  },
  "st50": {
   "name": "Wisconsin",
   "shortname": "WI",
   "comment": "",
   "link": "",
   "id": 50,
   "color": "#c89666",
   "colorOver": "#2d545e"
  },
  "st51": {
   "name": "Wyoming",
   "shortname": "WY",
   "comment": "",
   "link": "",
   "id": 51,
   "color": "#c89666",
   "colorOver": "#2d545e"
  }
 },
 "points": {
  "p0": {
   "x": 69.308,
   "y": 29.217,
   "color": "#2d545e",
   "colorOver": "#c89666",
   "name": "North Cascades National Park",
   "shortname": "Cascades",
   "pointType": "marker",
   "radius": 5,
   "textPos": "right-middle",
   "link": "www.travelwithdalt.com/post/north-cascades-national-park",
   "comment": ""
  },
  "p1": {
   "x": 87.654,
   "y": 308.487,
   "color": "#2d545e",
   "colorOver": "#c89666",
   "name": "Denali National Park",
   "shortname": "Denali",
   "pointType": "marker",
   "radius": 5,
   "textPos": "left-middle",
   "link": "www.travelwithdalt.com/post/denali-national-park",
   "comment": ""
  },
  "p2": {
   "x": 84.257,
   "y": 289.462,
   "color": "#2d545e",
   "colorOver": "#c89666",
   "name": "Gates of the Arctic National Park",
   "shortname": "Arctic",
   "pointType": "marker",
   "radius": 5,
   "textPos": "right-middle",
   "link": "www.travelwithdalt.com/post/gates-of-the-arctic-national-park",
   "comment": ""
  },
  "p3": {
   "x": 133.179,
   "y": 334.308,
   "color": "#2d545e",
   "colorOver": "#c89666",
   "name": "Glacier Bay National Park",
   "shortname": "Glacier Bay",
   "pointType": "marker",
   "radius": 5,
   "textPos": "middle-bottom",
   "link": "www.travelwithdalt.com/post/glacier-bay-national-park",
   "comment": ""
  },
  "p4": {
   "x": 76.782,
   "y": 332.269,
   "color": "#2d545e",
   "colorOver": "#c89666",
   "name": "Katmai National Park",
   "shortname": "Katmai",
   "pointType": "marker",
   "radius": 5,
   "textPos": "middle-bottom",
   "link": "www.travelwithdalt.com/post/katmai-national-park",
   "comment": ""
  },
  "p5": {
   "x": 93.769,
   "y": 319.359,
   "color": "#2d545e",
   "colorOver": "#c89666",
   "name": "Kenai Fjords National Park",
   "shortname": "Kenai",
   "pointType": "marker",
   "radius": 5,
   "textPos": "right-top",
   "link": "www.travelwithdalt.com/post/kenai-fjords-national-park",
   "comment": ""
  },
  "p6": {
   "x": 78.141,
   "y": 281.987,
   "color": "#2d545e",
   "colorOver": "#c89666",
   "name": "Kobuk Valley National Park",
   "shortname": "Kobuk",
   "pointType": "marker",
   "radius": 5,
   "textPos": "left-top",
   "link": "www.travelwithdalt.com/post/kobuk-valley-national-park",
   "comment": ""
  },
  "p7": {
   "x": 82.218,
   "y": 320.038,
   "color": "#2d545e",
   "colorOver": "#c89666",
   "name": "Lake Clark National Park",
   "shortname": "Lake Clark",
   "pointType": "marker",
   "radius": 5,
   "textPos": "left-middle",
   "link": "www.travelwithdalt.com/post/lake-clark-national-park",
   "comment": ""
  },
  "p8": {
   "x": 118.91,
   "y": 324.795,
   "color": "#2d545e",
   "colorOver": "#c89666",
   "name": "Wrangell-St. Elias National Park",
   "shortname": "W-St. E",
   "pointType": "marker",
   "radius": 5,
   "textPos": "right-middle",
   "link": "www.travelwithdalt.com/post/wrangell-st.-elias-national-park",
   "comment": ""
  },
  "p9": {
   "x": 6.795,
   "y": 240.538,
   "color": "#2d545e",
   "colorOver": "#c89666",
   "name": "National Park of American Samoa",
   "shortname": "Am. Samoa",
   "pointType": "marker",
   "radius": 5,
   "textPos": "right-middle",
   "link": "www.travelwithdalt.com/post/national-park-of-american-samoa",
   "comment": ""
  },
  "p10": {
   "x": 121.628,
   "y": 197.731,
   "color": "#2d545e",
   "colorOver": "#c89666",
   "name": "Petrified Forest National Park",
   "shortname": "Petrified Forest",
   "pointType": "marker",
   "radius": 5,
   "textPos": "right-middle",
   "link": "www.travelwithdalt.com/post/petrified-forest-national-park",
   "comment": ""
  },
  "p11": {
   "x": 103.282,
   "y": 223.552,
   "color": "#2d545e",
   "colorOver": "#c89666",
   "name": "Saguaro National Park",
   "shortname": "Saguaro",
   "pointType": "marker",
   "radius": 5,
   "textPos": "middle-bottom",
   "link": "www.travelwithdalt.com/post/saguaro-national-park",
   "comment": ""
  },
  "p12": {
   "x": 97.167,
   "y": 178.026,
   "color": "#2d545e",
   "colorOver": "#c89666",
   "name": "Grand Canyon National Park",
   "shortname": "Grand Canyon",
   "pointType": "marker",
   "radius": 5,
   "textPos": "middle-bottom",
   "link": "www.travelwithdalt.com/post/grand-canyon-national-park",
   "comment": ""
  },
  "p13": {
   "x": 275.871,
   "y": 218.795,
   "color": "#2d545e",
   "colorOver": "#c89666",
   "name": "Hot Springs National Park",
   "shortname": "Hot Springs",
   "pointType": "marker",
   "radius": 5,
   "textPos": "right-middle",
   "link": "www.travelwithdalt.com/post/hot-springs-national-park",
   "comment": ""
  },
  "p14": {
   "x": 27.179,
   "y": 186.86,
   "color": "#2d545e",
   "colorOver": "#c89666",
   "name": "Channel Islands National Park",
   "shortname": "Channel Is.",
   "pointType": "marker",
   "radius": 5,
   "textPos": "middle-bottom",
   "link": "www.travelwithdalt.com/post/channel-islands-national-park",
   "comment": ""
  },
  "p15": {
   "x": 66.589,
   "y": 203.846,
   "color": "#2d545e",
   "colorOver": "#c89666",
   "name": "Joshua Tree National Park",
   "shortname": "J Tree",
   "pointType": "marker",
   "radius": 5,
   "textPos": "middle-bottom",
   "link": "www.travelwithdalt.com/post/joshua-tree-national-park",
   "comment": ""
  },
  "p16": {
   "x": 42.808,
   "y": 156.283,
   "color": "#2d545e",
   "colorOver": "#c89666",
   "name": "Kings Canyon National Park",
   "shortname": "‎ ‎‎  ‎ ‎Kings  ‎ ‎ Canyon",
   "pointType": "marker",
   "radius": 5,
   "textPos": "middle-middle",
   "link": "www.travelwithdalt.com/post/kings-canyon-national-park",
   "comment": ""
  },
  "p17": {
   "x": 38.052,
   "y": 110.076,
   "color": "#2d545e",
   "colorOver": "#c89666",
   "name": "Lassen Volcanic National Park",
   "shortname": "Lassen",
   "pointType": "marker",
   "radius": 5,
   "textPos": "right-middle",
   "link": "www.travelwithdalt.com/post/lassen-volcanic-national-park",
   "comment": ""
  },
  "p18": {
   "x": 19.024,
   "y": 147.448,
   "color": "#2d545e",
   "colorOver": "#c89666",
   "name": "Pinnacles National Park",
   "shortname": "Pinnacles",
   "pointType": "marker",
   "radius": 5,
   "textPos": "right-middle",
   "link": "www.travelwithdalt.com/post/pinnacles-national-park",
   "comment": ""
  },
  "p19": {
   "x": 14.949,
   "y": 99.205,
   "color": "#2d545e",
   "colorOver": "#c89666",
   "name": "Redwood National Park",
   "shortname": "Redwood",
   "pointType": "marker",
   "radius": 5,
   "textPos": "right-middle",
   "link": "www.travelwithdalt.com/post/redwood-national-park",
   "comment": ""
  },
  "p20": {
   "x": 44.846,
   "y": 174.627,
   "color": "#2d545e",
   "colorOver": "#c89666",
   "name": "Sequoia National Park",
   "shortname": "Sequoia",
   "pointType": "marker",
   "radius": 5,
   "textPos": "left-middle",
   "link": "www.travelwithdalt.com/post/sequoia-national-park",
   "comment": ""
  },
  "p21": {
   "x": 36.694,
   "y": 140.656,
   "color": "#2d545e",
   "colorOver": "#c89666",
   "name": "Yosemite National Park",
   "shortname": "Yosemite",
   "pointType": "marker",
   "radius": 5,
   "textPos": "middle-top",
   "link": "www.travelwithdalt.com/post/yosemite-national-park",
   "comment": ""
  },
  "p22": {
   "x": 41.449,
   "y": 167.154,
   "color": "#2d545e",
   "colorOver": "#c89666",
   "name": "Death Valley National Park",
   "shortname": "DeathValley‎",
   "pointType": "marker",
   "radius": 5,
   "textPos": "left-middle",
   "link": "www.travelwithdalt.com/post/death-valley-national-park",
   "comment": ""
  },
  "p23": {
   "x": 144.051,
   "y": 156.283,
   "color": "#2d545e",
   "colorOver": "#c89666",
   "name": "Black Canyon of the Gunnison National Park",
   "shortname": "Black Canyon",
   "pointType": "marker",
   "radius": 5,
   "textPos": "right-middle",
   "link": "www.travelwithdalt.com/post/black-canyon-of-the-gunnison-national-park",
   "comment": ""
  },
  "p24": {
   "x": 167.154,
   "y": 169.192,
   "color": "#2d545e",
   "colorOver": "#c89666",
   "name": "Great Sand Dunes National Park",
   "shortname": "Sand Dunes",
   "pointType": "marker",
   "radius": 5,
   "textPos": "right-middle",
   "link": "www.travelwithdalt.com/post/great-sand-dunes-national-park",
   "comment": ""
  },
  "p25": {
   "x": 139.294,
   "y": 169.194,
   "color": "#2d545e",
   "colorOver": "#c89666",
   "name": "Mesa Verde National Park",
   "shortname": "Mesa Verde",
   "pointType": "marker",
   "radius": 5,
   "textPos": "right-bottom",
   "link": "www.travelwithdalt.com/post/mesa-verde-national-park",
   "comment": ""
  },
  "p26": {
   "x": 154.923,
   "y": 142.692,
   "color": "#2d545e",
   "colorOver": "#c89666",
   "name": "Rocky Mountain National Park",
   "shortname": "Rocky Mtn.",
   "pointType": "marker",
   "radius": 5,
   "textPos": "right-middle",
   "link": "www.travelwithdalt.com/post/rocky-mountain-national-park",
   "comment": ""
  },
  "p27": {
   "x": 416.526,
   "y": 293.538,
   "color": "#2d545e",
   "colorOver": "#c89666",
   "name": "Biscayne National Park",
   "shortname": "Biscayne",
   "pointType": "marker",
   "radius": 5,
   "textPos": "right-middle",
   "link": "www.travelwithdalt.com/post/biscayne-national-park",
   "comment": ""
  },
  "p28": {
   "x": 405.653,
   "y": 310.526,
   "color": "#2d545e",
   "colorOver": "#c89666",
   "name": "Dry Tortugas National Park",
   "shortname": "Dry Tortugas",
   "pointType": "marker",
   "radius": 5,
   "textPos": "left-bottom",
   "link": "www.travelwithdalt.com/post/dry-tortugas-national-park",
   "comment": ""
  },
  "p29": {
   "x": 407.692,
   "y": 296.936,
   "color": "#2d545e",
   "colorOver": "#c89666",
   "name": "Everglades National Park",
   "shortname": "Everglades",
   "pointType": "marker",
   "radius": 5,
   "textPos": "left-middle",
   "link": "www.travelwithdalt.com/post/everglades-national-park",
   "comment": ""
  },
  "p30": {
   "x": 192.975,
   "y": 316.642,
   "color": "#2d545e",
   "colorOver": "#c89666",
   "name": "Haleakala National Park",
   "shortname": "Haleakala",
   "pointType": "marker",
   "radius": 5,
   "textPos": "right-middle",
   "link": "www.travelwithdalt.com/post/haleakala-national-park",
   "comment": ""
  },
  "p31": {
   "x": 203.167,
   "y": 331.589,
   "color": "#2d545e",
   "colorOver": "#c89666",
   "name": "Hawai’i Volcanoes National Park",
   "shortname": "Volcanoes",
   "pointType": "marker",
   "radius": 5,
   "textPos": "right-middle",
   "link": "www.travelwithdalt.com/post/hawai’i-volcanoes-national-park",
   "comment": ""
  },
  "p32": {
   "x": 142.692,
   "y": 87.654,
   "color": "#2d545e",
   "colorOver": "#c89666",
   "name": "Yellowstone National Park",
   "shortname": "Yellowstone",
   "pointType": "marker",
   "radius": 5,
   "textPos": "middle-top",
   "link": "www.travelwithdalt.com/post/yellowstone-national-park",
   "comment": ""
  },
  "p33": {
   "x": 330.231,
   "y": 129.103,
   "color": "#2d545e",
   "colorOver": "#c89666",
   "name": "Indiana Dunes National Park",
   "shortname": "IN Dunes",
   "pointType": "marker",
   "radius": 5,
   "textPos": "middle-bottom",
   "link": "www.travelwithdalt.com/post/indiana-dunes-national-park",
   "comment": ""
  },
  "p34": {
   "x": 335.667,
   "y": 182.103,
   "color": "#2d545e",
   "colorOver": "#c89666",
   "name": "Mammoth Cave National Park",
   "shortname": "Mammoth",
   "pointType": "marker",
   "radius": 5,
   "textPos": "left-middle",
   "link": "www.travelwithdalt.com/post/mammoth-cave-national-park",
   "comment": ""
  },
  "p35": {
   "x": 473.603,
   "y": 78.141,
   "color": "#2d545e",
   "colorOver": "#c89666",
   "name": "Acadia National Park",
   "shortname": "Acadia",
   "pointType": "marker",
   "radius": 5,
   "textPos": "left-middle",
   "link": "www.travelwithdalt.com/post/acadia-national-park",
   "comment": ""
  },
  "p36": {
   "x": 325.474,
   "y": 66.59,
   "color": "#2d545e",
   "colorOver": "#c89666",
   "name": "Isle Royale National Park",
   "shortname": "‎ ‎ ‎‎ ‎‎‎ ‎  ‎‎  Isle‎ ‎ ‎ Royale‎‎‎",
   "pointType": "marker",
   "radius": 5,
   "textPos": "middle-middle",
   "link": "www.travelwithdalt.com/post/isle-royale-national-park",
   "comment": ""
  },
  "p37": {
   "x": 264.999,
   "y": 55.717,
   "color": "#2d545e",
   "colorOver": "#c89666",
   "name": "Voyageurs National Park",
   "shortname": "Voyageurs",
   "pointType": "marker",
   "radius": 5,
   "textPos": "middle-top",
   "link": "www.travelwithdalt.com/post/voyageurs-national-park",
   "comment": ""
  },
  "p38": {
   "x": 303.051,
   "y": 168.513,
   "color": "#2d545e",
   "colorOver": "#c89666",
   "name": "Gateway Arch National Park",
   "shortname": "Gateway Arch",
   "pointType": "marker",
   "radius": 5,
   "textPos": "middle-top",
   "link": "www.travelwithdalt.com/post/gateway-arch-national-park",
   "comment": ""
  },
  "p39": {
   "x": 119.59,
   "y": 40.769,
   "color": "#2d545e",
   "colorOver": "#c89666",
   "name": "Glacier National Park",
   "shortname": "Glacier",
   "pointType": "marker",
   "radius": 5,
   "textPos": "middle-bottom",
   "link": "www.travelwithdalt.com/post/glacier-national-park",
   "comment": ""
  },
  "p40": {
   "x": 88.333,
   "y": 139.294,
   "color": "#2d545e",
   "colorOver": "#c89666",
   "name": "Great Basin National Park",
   "shortname": "Great Basin",
   "pointType": "marker",
   "radius": 5,
   "textPos": "middle-top",
   "link": "www.travelwithdalt.com/post/great-basin-national-park",
   "comment": ""
  },
  "p41": {
   "x": 170.551,
   "y": 228.308,
   "color": "#2d545e",
   "colorOver": "#c89666",
   "name": "Carlsbad Caverns National Park",
   "shortname": "‎Carlsbad‎‎ ‎ ‎‎ ‎ ‎‎Caverns‎ ‎",
   "pointType": "marker",
   "radius": 5,
   "textPos": "middle-middle",
   "link": "www.travelwithdalt.com/post/carlsbad-caverns-national-park",
   "comment": ""
  },
  "p42": {
   "x": 158.321,
   "y": 218.116,
   "color": "#2d545e",
   "colorOver": "#c89666",
   "name": "White Sands National Park",
   "shortname": "‎ White‎‎‎‎ ‎‎  ‎ ‎‎Sands",
   "pointType": "marker",
   "radius": 5,
   "textPos": "middle-middle",
   "link": "www.travelwithdalt.com/post/white-sands-national-park",
   "comment": ""
  },
  "p43": {
   "x": 366.923,
   "y": 192.295,
   "color": "#2d545e",
   "colorOver": "#c89666",
   "name": "Great Smoky Mountains National Park",
   "shortname": "Smokies",
   "pointType": "marker",
   "radius": 5,
   "textPos": "middle-bottom",
   "link": "www.travelwithdalt.com/post/great-smoky-mountains-national-park",
   "comment": ""
  },
  "p44": {
   "x": 190.936,
   "y": 67.949,
   "color": "#2d545e",
   "colorOver": "#c89666",
   "name": "Theodore Roosevelt National Park",
   "shortname": "T. Roosevelt",
   "pointType": "marker",
   "radius": 5,
   "textPos": "middle-top",
   "link": "www.travelwithdalt.com/post/theodore-roosevelt-national-park",
   "comment": ""
  },
  "p45": {
   "x": 378.473,
   "y": 129.102,
   "color": "#2d545e",
   "colorOver": "#c89666",
   "name": "Cuyahoga Valley National Park",
   "shortname": "Cuyahoga",
   "pointType": "marker",
   "radius": 5,
   "textPos": "middle-top",
   "link": "www.travelwithdalt.com/post/cuyahoga-valley-national-park",
   "comment": ""
  },
  "p46": {
   "x": 28.538,
   "y": 82.218,
   "color": "#2d545e",
   "colorOver": "#c89666",
   "name": "Crater Lake National Park",
   "shortname": "Crater lake",
   "pointType": "marker",
   "radius": 5,
   "textPos": "middle-top",
   "link": "www.travelwithdalt.com/post/crater-lake-national-park",
   "comment": ""
  },
  "p47": {
   "x": 400.218,
   "y": 216.076,
   "color": "#2d545e",
   "colorOver": "#c89666",
   "name": "Congaree National Park",
   "shortname": "Congaree",
   "pointType": "marker",
   "radius": 5,
   "textPos": "right-bottom",
   "link": "www.travelwithdalt.com/post/congaree-national-park",
   "comment": ""
  },
  "p48": {
   "x": 201.128,
   "y": 109.397,
   "color": "#2d545e",
   "colorOver": "#c89666",
   "name": "Badlands National Park",
   "shortname": "Badlands",
   "pointType": "marker",
   "radius": 5,
   "textPos": "right-middle",
   "link": "www.travelwithdalt.com/post/badlands-national-park",
   "comment": ""
  },
  "p49": {
   "x": 188.897,
   "y": 107.359,
   "color": "#2d545e",
   "colorOver": "#c89666",
   "name": "Wind Cave National Park",
   "shortname": "Wind Cave",
   "pointType": "marker",
   "radius": 5,
   "textPos": "middle-bottom",
   "link": "www.travelwithdalt.com/post/wind-cave-national-park",
   "comment": ""
  },
  "p50": {
   "x": 175.988,
   "y": 265.679,
   "color": "#2d545e",
   "colorOver": "#c89666",
   "name": "Big Bend National Park",
   "shortname": "Big Bend",
   "pointType": "marker",
   "radius": 5,
   "textPos": "right-middle",
   "link": "www.travelwithdalt.com/post/big-bend-national-park",
   "comment": ""
  },
  "p51": {
   "x": 167.153,
   "y": 237.821,
   "color": "#2d545e",
   "colorOver": "#c89666",
   "name": "Guadalupe Mountains National Park",
   "shortname": "Guadalupe",
   "pointType": "marker",
   "radius": 5,
   "textPos": "middle-bottom",
   "link": "www.travelwithdalt.com/post/guadalupe-mountains-national-park",
   "comment": ""
  },
  "p52": {
   "x": 131.82,
   "y": 152.205,
   "color": "#2d545e",
   "colorOver": "#c89666",
   "name": "Arches National Park",
   "shortname": "Arches",
   "pointType": "marker",
   "radius": 5,
   "textPos": "middle-top",
   "link": "www.travelwithdalt.com/post/arches-national-park",
   "comment": ""
  },
  "p53": {
   "x": 103.282,
   "y": 163.756,
   "color": "#2d545e",
   "colorOver": "#c89666",
   "name": "Bryce Canyon National Park",
   "shortname": "Bryce",
   "pointType": "marker",
   "radius": 5,
   "textPos": "middle-top",
   "link": "www.travelwithdalt.com/post/bryce-canyon-national-park",
   "comment": ""
  },
  "p54": {
   "x": 123.667,
   "y": 160.359,
   "color": "#2d545e",
   "colorOver": "#c89666",
   "name": "Canyonlands National Park",
   "shortname": "CL",
   "pointType": "marker",
   "radius": 5,
   "textPos": "right-middle",
   "link": "www.travelwithdalt.com/post/canyonlands-national-park",
   "comment": ""
  },
  "p55": {
   "x": 114.833,
   "y": 161.718,
   "color": "#2d545e",
   "colorOver": "#c89666",
   "name": "Capitol Reef National Park",
   "shortname": "CR",
   "pointType": "marker",
   "radius": 5,
   "textPos": "middle-bottom",
   "link": "www.travelwithdalt.com/post/capitol-reef-national-park",
   "comment": ""
  },
  "p56": {
   "x": 91.731,
   "y": 163.077,
   "color": "#2d545e",
   "colorOver": "#c89666",
   "name": "Zion National Park",
   "shortname": "Zion",
   "pointType": "marker",
   "radius": 5,
   "textPos": "left-bottom",
   "link": "www.travelwithdalt.com/post/zion-national-park",
   "comment": ""
  },
  "p57": {
   "x": 525.922,
   "y": 399.537,
   "color": "#2d545e",
   "colorOver": "#c89666",
   "name": "Virgin Islands National Park",
   "shortname": "Virgin Islands",
   "pointType": "marker",
   "radius": 5,
   "textPos": "left-middle",
   "link": "www.travelwithdalt.com/post/virgin-islands-national-park",
   "comment": ""
  },
  "p58": {
   "x": 417.205,
   "y": 153.564,
   "color": "#2d545e",
   "colorOver": "#c89666",
   "name": "Shenandoah National Park",
   "shortname": "Shenandoah",
   "pointType": "marker",
   "radius": 5,
   "textPos": "middle-top",
   "link": "www.travelwithdalt.com/post/shenandoah-national-park",
   "comment": ""
  },
  "p59": {
   "x": 48.244,
   "y": 57.077,
   "color": "#2d545e",
   "colorOver": "#c89666",
   "name": "Mount Rainier National Park",
   "shortname": "Rainier",
   "pointType": "marker",
   "radius": 5,
   "textPos": "right-middle",
   "link": "www.travelwithdalt.com/post/mount-rainier-national-park",
   "comment": ""
  },
  "p60": {
   "x": 35.332,
   "y": 33.975,
   "color": "#2d545e",
   "colorOver": "#c89666",
   "name": "Olympic National Park",
   "shortname": "Olympic",
   "pointType": "marker",
   "radius": 5,
   "textPos": "middle-top",
   "link": "www.travelwithdalt.com/post/olympic-national-park",
   "comment": ""
  },
  "p61": {
   "x": 387.987,
   "y": 169.192,
   "color": "#2d545e",
   "colorOver": "#c89666",
   "name": "New River Gorge National Park",
   "shortname": "Gorge",
   "pointType": "marker",
   "radius": 5,
   "textPos": "middle-bottom",
   "link": "www.travelwithdalt.com/post/new-river-gorge-national-park",
   "comment": ""
  },
  "p62": {
   "x": 131.142,
   "y": 102.603,
   "color": "#2d545e",
   "colorOver": "#c89666",
   "name": "Grand Teton National Park",
   "shortname": "‎ ‎Grand ‎ ‎ ‎‎Tetons",
   "pointType": "marker",
   "radius": 5,
   "textPos": "middle-middle",
   "link": "www.travelwithdalt.com/post/grand-teton-national-park",
   "comment": ""
  }
 }
};
